### ISSUE TITLE
PhasePlot does not accept data as a list

### ISSUE THREAD

**Issue by samwalkow** [data-exp-lab/analysis_schema#33]
### Description

`PhasePlot`, by design in yt, only accepts a data source. So the `PhasePlot` currently only accepts a single `Dataset` but there is no way to specify a list either within the `PhasePlot` specification or at the top of the document.

### What I Did

This works:

```json
{
    "$schema": "../analysis_schema/yt_analysis_schema.json",
    "Plot": [
        {
            "PhasePlot": {
                "Dataset": {  
                    "FileName": "IsolatedGalaxy/galaxy0030/galaxy0030",
                    "DatasetName": "IG"
# no list is available to specify multiple datasets.
                },
                "Axis": "x",
                "xField": {
                    "field": "density",
                    "field_type": "gas"
                },
                "yField": {
                    "field": "temperature",
                    "field_type": "gas"
                },
                "zField(s)":{
                    "field": "pressure",
                    "field_type": "gas"
                },
                "output_type": "file"
            }
        }
    ]
  }
```

This doesn't work:

```json
{
    "$schema": "../analysis_schema/yt_analysis_schema.json",
    "Plot": [
        {
            "PhasePlot": {
                "Dataset": [
                    {
                    "FileName": "IsolatedGalaxy/galaxy0030/galaxy0030",
                    "DatasetName": "IG"
                }
            ],
# this isn't valid input for the `Dataset` keyword
                "Axis": "x",
                "xField": {
                    "field": "density",
                    "field_type": "gas"
                },
                "yField": {
                    "field": "temperature",
                    "field_type": "gas"
                },
                "zField(s)":{
                    "field": "pressure",
                    "field_type": "gas"
                },
                "output_type": "file"
            }
        }
    ]
  }

```

This also doesn't work:

```json
{
    "$schema": "../analysis_schema/yt_analysis_schema.json",
    "Dataset": [
        {
        "FileName": "IsolatedGalaxy/galaxy0030/galaxy0030",
        "DatasetName": "IG"
        }
    ],
# data is declared at the top. It's valid, but I get an error when I run it, I've included it below. 
    "Plot": [
        {
            "PhasePlot": {
                "Axis": "x",
                "xField": {
                    "field": "density",
                    "field_type": "gas"
                },
                "yField": {
                    "field": "temperature",
                    "field_type": "gas"
                },
                "zField(s)":{
                    "field": "pressure",
                    "field_type": "gas"
                },
                "output_type": "file"
            }
        }
    ]
  }

```
The error I get is: 

```
Traceback (most recent call last):
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/run_analysis.py", line 30, in <module>
    load_and_run(args.JSONFile)
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/run_analysis.py", line 16, in load_and_run
    return wk.run_all()
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/_workflows.py", line 95, in run_all
    output.append(workflow.run())
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/_workflows.py", line 25, in run
    return runner.run(self.model, ds=ds)
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/_model_instantiation.py", line 17, in run
    return self.process_pydantic(pydantic_instance, ds=ds)
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/_model_instantiation.py", line 161, in process_pydantic
    result = generic_runner.run(viz_model, ds=ds)
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/_model_instantiation.py", line 17, in run
    return self.process_pydantic(pydantic_instance, ds=ds)
  File "/Users/swalkow2/Documents/Analysis_Schema_Project/analysis_schema/analysis_schema/_model_instantiation.py", line 130, in process_pydantic
    return yt_func(*the_args, **kwarg_dict)
  File "/Users/swalkow2/opt/miniconda3/envs/Analysis_Schema-venv/lib/python3.9/site-packages/yt/visualization/profile_plotter.py", line 962, in __init__
    data_source = data_object_or_all_data(data_source)
  File "/Users/swalkow2/opt/miniconda3/envs/Analysis_Schema-venv/lib/python3.9/site-packages/yt/visualization/profile_plotter.py", line 114, in data_object_or_all_data
    raise RuntimeError("data_source must be a yt selection data object")
RuntimeError: data_source must be a yt selection data object

```

**Comment by chrishavlin** [comment]
Good catch! Two issues I think. First is just our pydantic model definition doesn't have the `Dataset` in a list like the Slice and Projection plots have: 

```python
class PhasePlot(ytVisualization):
    """A yt phase plot"""

    data_source: Optional[Dataset] = Field(alias="Dataset")
    ....
```

the second (and more important) issue is, like you said, that the `data_source` argument to `PhasePlot` is a yt `data_source`, not a dataset. So I think we should correct that in our model :) One possibility is to add a `ds` attribute to the model to match `SlicePlot` and `ProjectionPlot` better and then adjust the model instantiation a little. So:

```python
class PhasePlot(ytVisualization):
    """A yt phase plot"""

    ds: Optional[List[Dataset]]
    data_source: Optional[DataSource3D]
    ....
```

and then add a new `PhasePlot` runner to `_model_instantiation` that gets the `data_source` object ready for `PhasePlot` (if no `data_source` is set, use `ds.all_data()` (note the `Visualizations` runner would have to be adjusted a little as well).
